version: '3.3'

services:
  helloworld:
    image: stefanscherer/whoami
    ports:
      - '8000:8080'
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
          - node.labels.os == linux
