version: '3.3'

services:
  helloworld:
    image: tutum/hello-world
    ports:
      - '80:80'
    networks:
      - hellonet
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
          - node.labels.os == linux

networks:
  hellonet:
