version: '3.3'

services:
  elasticsearch:
    build: elasticsearch
    image: 127.0.0.1:5000/elk/elasticsearch:latest
    environment:
      http.host: '0.0.0.0'
      transport.host: '127.0.0.1'
      cluster.name: 'docker-cluster'
      boostrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    volumes:
      - esdata:/opt/elasticsearch/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

volumes:
  esdata:
    driver: rexray
    driver_opts:
      size: 2

networks:
  esnet:
