version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    networks:
      - esnet
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    networks:
      - esnet
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      XPACK_SECURITY_ENABLED: 'false'
      XPACK_MONITORING_ENABLED: 'false'
  # logstash:
  #   image: docker.elastic.co/logstash/logstash:5.5.2
  #   networks:
  #     - esnet
  #   ports:
  #     - '12201:12201/udp'
  #   volumes:
  #     - ./logstash/logstash.conf/:/usr/share/logstash/pipeline/logstash.conf
  #   depends_on:
  #     - elasticsearch

volumes:
  esdata:
    driver: local

networks:
  esnet:
