---

- hosts: manager
  become: true
  roles:
    - swarm-manager

- hosts: swarm_manager_bootstrap[0]
  become: true
  roles:
    - swarm-manager-bootstrap


- hosts: swarm_manager_operational[0]
  become: true
  vars:
    iface: "{{ swarm_iface | default('eth0') }}"
  roles:
    - swarm-manager-operational


- hosts: swarm_manager_bootstrap:!swarm_manager_operational
  become: true
  vars:
    token: "{{ hostvars[groups['swarm_manager_operational'][0]]['swarm_manager_token']['stdout'] }}"
  roles:
    - swarm-manager-join


- hosts: worker
  become: true
  roles:
    - swarm-worker


- hosts: swarm_worker_bootstrap
  become: true
  vars:
    token: "{{ hostvars[groups['swarm_manager_operational'][0]]['swarm_worker_token']['stdout'] }}"
  roles:
    - swarm-worker-bootstrap
